### PR TITLE
add filterWarnings config

### PR DESCRIPTION
**Pull request by SimeonGriggs**
Added `filterWarnings` config and updated Readme.

The config's API allows you to check for multiple conditions with AND and OR logic.

```json
"filterWarnings": [
  {"_type": "article", "title.en": "Hello!"},
  {"isLive": true},
]
```

If **all** of the keys have a matching value in **any** of the objects in the array – warnings will be hidden.

### CODE REVIEW

**Comment by runeb** [comment]
Interesting! I would have guessed the main use case to be ignoring any value change in a given field name. Say if you have `reviewStatus` which can be `waiting`, `approved` or `rejected` maybe you don't want to warn that the document has changed if the field is set to any of those. Can you do that with this config? My first idea was something like this

```json
{
      "type": "post",
      "field": "publishedAt",
      "titleField": "title",
      "suppressWarningsOn": ["reviewStatus"]
    }
```

**Comment by runeb** [comment]
I may have misunderstood the use case!

**Comment by SimeonGriggs** [comment]
You could still do that with this API, this config would remove the warnings if any of these return true.

```json
"filterWarnings": [
  {"reviewStatus": "waiting"},
  {"reviewStatus": "approved"},
  {"reviewStatus": "rejected"},
]
```

The request for this feature was plainly "does the field on this document equal a certain value".

**Review by runeb — APPROVED** [review]
LGMT

**Pull request merged**
